from enum import Enum

class CMD(Enum):
    PING = 0
    SEND_TWO_INTS = 1
    SEND_THREE_FLOATS = 2
    ECHO = 3
    DANCE = 4
    SET_VEL = 5
    GET_TIME_MILLIS = 6
    TIME_LOOP = 7
    SEND_TIME_DATA = 8
    GET_TEMP_READINGS = 9
    READ_IMU_TOF = 10
    SET_PID_GAINS = 11
    START_PID_LOG = 12
    STOP_PID_LOG = 13
    SEND_PID_LOG = 14
    START_PID_RATE_TEST = 15
    SEND_PID_RATE_TEST = 16
    PID_ORIENTATION = 17
    STOP_ORIENTATION_PID = 18
    SEND_ANGULAR_DATA = 19
    SET_ANGULAR_SETPOINT = 20
    START_STEP_RESPONSE = 21
    STOP_STEP_RESPONSE = 22
    SEND_STEP_RESPONSE = 23
    START_KF_PID_LOG = 24
    STOP_KF_PID_LOG = 25
    SEND_KF_LOG = 26
    START_DRIFT = 27
    STOP_DRIFT = 28
    SEND_DRIFT_LOG = 29